# src/examples/CMakeLists.txt                                       -*-cmake-*-
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

include(${PROJECT_SOURCE_DIR}/cmake/add_paired_example.cmake)

add_subdirectory(consteval)
add_subdirectory(donotation)
add_subdirectory(gating)
add_subdirectory(ranges)
add_subdirectory(scorecard)
add_subdirectory(senders)
